
exports.seed = function(knex, Promise) {
  return knex('recipe').del()
    .then(function () {
      return knex('recipe').insert([
        // {url: 'https://minimalistbaker.com/southwest-tofu-scramble/', name: 'Southwest Tofu Scramble', category: 'breakfast', ingredients: ['8 ounces of tofu', '1/4 onion', '1/2 red pepper', '2 cups of kale', '1/2 teaspoon of salt', '1/2 teaspoon garlic powder', '1/2 teaspoon cumin', '1/4 teaspoon chili powder', 'tumeric'], instructions: ['Pat tofu dry for 15 minutes.', 'Prepare sauce, Set aside.', 'Prep veggies and warm a large skillet over medium heat. Once hot, add olive oil and the onion and red pepper. Season with a pinch each salt and pepper and stir. Cook until softened - about 5 minutes.', 'Add kale, season with a bit more salt and pepper, and cover to steam for 2 minutes.', 'crumble tofu and add to pan, add sauce, and cook a little more']},
        // {url: 'url2', name: 'name2', category: 'breakfast', ingredients: ['ingredient1', 'ingredient 2', 'ingredient 3'], instructions: ['step 1', 'step 2', 'step 3']},
        // {url: 'url3', name: 'name3', category: 'breakfast', ingredients: ['ingredient1', 'ingredient 2', 'ingredient 3'], instructions: ['step 1', 'step 2', 'step 3']},
        // {url: 'url4', name: 'name4', category: 'breakfast', ingredients: ['ingredient1', 'ingredient 2', 'ingredient 3'], instructions: ['step 1', 'step 2', 'step 3']},
        // {url: 'url5', name: 'name5', category: 'breakfast', ingredients: ['ingredient1', 'ingredient 2', 'ingredient 3'], instructions: ['step 1', 'step 2', 'step 3']},

        {url: 'https://www.halfbakedharvest.com/firey-schezwan-peanut-and-chili-zucchini-noodles/', name: 'Pasta and Zoodles and Peanut Sauce', category: 'dinner', ingredients: ['half bag of pasta', '1/4 cup of peanut butter', '1/4 cup of tahini', '2 tablespoons of soy sauce', '2 tablespoons of honey', '2 tablespoons of lime juice', '2 teaspons of seasame oil', '1/4 cup of coconut milk', '3 medium zucchinis', '1/2 cup of peanuts', '2 tablespoons of seasame seeds', '1/2 cup of cilantro', 'bell peppers'], instructions: ['make sauce', 'cook pasta', 'spiralize zucchinis', 'add sauce and zoodles in a bowl', 'drain pasta and add to bowl', 'mix well and add roasted nuts on top']},
        {url: 'https://minimalistbaker.com/southwest-tofu-scramble/', name: 'Southwest Tofu Scramble', category: 'dinner', ingredients: ['8 ounces of tofu', '1/4 onion', '1/2 red pepper', '2 cups of kale', '1/2 teaspoon of salt', '1/2 teaspoon garlic powder', '1/2 teaspoon cumin', '1/4 teaspoon chili powder', 'tumeric'], instructions: ['Pat tofu dry for 15 minutes.', 'Prepare sauce, Set aside.', 'Prep veggies and warm a large skillet over medium heat. Once hot, add olive oil and the onion and red pepper. Season with a pinch each salt and pepper and stir. Cook until softened - about 5 minutes.', 'Add kale, season with a bit more salt and pepper, and cover to steam for 2 minutes.', 'crumble tofu and add to pan, add sauce, and cook a little more']},
        {url: 'https://www.halfbakedharvest.com/firey-schezwan-peanut-and-chili-zucchini-noodles/', name: 'Pasta and Zoodles and Peanut Sauce', category: 'dinner', ingredients: ['half bag of pasta', '1/4 cup of peanut butter', '1/4 cup of tahini', '2 tablespoons of soy sauce', '2 tablespoons of honey', '2 tablespoons of lime juice', '2 teaspons of seasame oil', '1/4 cup of coconut milk', '3 medium zucchinis', '1/2 cup of peanuts', '2 tablespoons of seasame seeds', '1/2 cup of cilantro', 'bell peppers'], instructions: ['make sauce', 'cook pasta', 'spiralize zucchinis', 'add sauce and zoodles in a bowl', 'drain pasta and add to bowl', 'mix well and add roasted nuts on top']},
        {url: 'https://minimalistbaker.com/southwest-tofu-scramble/', name: 'Southwest Tofu Scramble', category: 'dinner', ingredients: ['8 ounces of tofu', '1/4 onion', '1/2 red pepper', '2 cups of kale', '1/2 teaspoon of salt', '1/2 teaspoon garlic powder', '1/2 teaspoon cumin', '1/4 teaspoon chili powder', 'tumeric'], instructions: ['Pat tofu dry for 15 minutes.', 'Prepare sauce, Set aside.', 'Prep veggies and warm a large skillet over medium heat. Once hot, add olive oil and the onion and red pepper. Season with a pinch each salt and pepper and stir. Cook until softened - about 5 minutes.', 'Add kale, season with a bit more salt and pepper, and cover to steam for 2 minutes.', 'crumble tofu and add to pan, add sauce, and cook a little more']},
        {url: 'https://www.halfbakedharvest.com/firey-schezwan-peanut-and-chili-zucchini-noodles/', name: 'Pasta and Zoodles and Peanut Sauce', category: 'dinner', ingredients: ['half bag of pasta', '1/4 cup of peanut butter', '1/4 cup of tahini', '2 tablespoons of soy sauce', '2 tablespoons of honey', '2 tablespoons of lime juice', '2 teaspons of seasame oil', '1/4 cup of coconut milk', '3 medium zucchinis', '1/2 cup of peanuts', '2 tablespoons of seasame seeds', '1/2 cup of cilantro', 'bell peppers'], instructions: ['make sauce', 'cook pasta', 'spiralize zucchinis', 'add sauce and zoodles in a bowl', 'drain pasta and add to bowl', 'mix well and add roasted nuts on top']},
        {url: 'https://minimalistbaker.com/southwest-tofu-scramble/', name: 'Southwest Tofu Scramble', category: 'dinner', ingredients: ['8 ounces of tofu', '1/4 onion', '1/2 red pepper', '2 cups of kale', '1/2 teaspoon of salt', '1/2 teaspoon garlic powder', '1/2 teaspoon cumin', '1/4 teaspoon chili powder', 'tumeric'], instructions: ['Pat tofu dry for 15 minutes.', 'Prepare sauce, Set aside.', 'Prep veggies and warm a large skillet over medium heat. Once hot, add olive oil and the onion and red pepper. Season with a pinch each salt and pepper and stir. Cook until softened - about 5 minutes.', 'Add kale, season with a bit more salt and pepper, and cover to steam for 2 minutes.', 'crumble tofu and add to pan, add sauce, and cook a little more']},
        {url: 'https://www.halfbakedharvest.com/firey-schezwan-peanut-and-chili-zucchini-noodles/', name: 'Pasta and Zoodles and Peanut Sauce', category: 'dinner', ingredients: ['half bag of pasta', '1/4 cup of peanut butter', '1/4 cup of tahini', '2 tablespoons of soy sauce', '2 tablespoons of honey', '2 tablespoons of lime juice', '2 teaspons of seasame oil', '1/4 cup of coconut milk', '3 medium zucchinis', '1/2 cup of peanuts', '2 tablespoons of seasame seeds', '1/2 cup of cilantro', 'bell peppers'], instructions: ['make sauce', 'cook pasta', 'spiralize zucchinis', 'add sauce and zoodles in a bowl', 'drain pasta and add to bowl', 'mix well and add roasted nuts on top']},
        {url: 'https://minimalistbaker.com/southwest-tofu-scramble/', name: 'Southwest Tofu Scramble', category: 'dinner', ingredients: ['8 ounces of tofu', '1/4 onion', '1/2 red pepper', '2 cups of kale', '1/2 teaspoon of salt', '1/2 teaspoon garlic powder', '1/2 teaspoon cumin', '1/4 teaspoon chili powder', 'tumeric'], instructions: ['Pat tofu dry for 15 minutes.', 'Prepare sauce, Set aside.', 'Prep veggies and warm a large skillet over medium heat. Once hot, add olive oil and the onion and red pepper. Season with a pinch each salt and pepper and stir. Cook until softened - about 5 minutes.', 'Add kale, season with a bit more salt and pepper, and cover to steam for 2 minutes.', 'crumble tofu and add to pan, add sauce, and cook a little more']},

        // {url: 'url2', name: 'name2', category: 'dinner', ingredients: ['ingredient1', 'ingredient 2', 'ingredient 3'], instructions: ['step 1', 'step 2', 'step 3']},
        // {url: 'url3', name: 'name3', category: 'dinner', ingredients: ['ingredient1', 'ingredient 2', 'ingredient 3'], instructions: ['step 1', 'step 2', 'step 3']},
        // {url: 'url4', name: 'name4', category: 'dinner', ingredients: ['ingredient1', 'ingredient 2', 'ingredient 3'], instructions: ['step 1', 'step 2', 'step 3']},
        // {url: 'url5', name: 'name5', category: 'dinner', ingredients: ['ingredient1', 'ingredient 2', 'ingredient 3'], instructions: ['step 1', 'step 2', 'step 3']},
        //
        // {url: 'url1', name: 'name1', category: 'drinks', ingredients: ['ingredient1', 'ingredient 2', 'ingredient 3'], instructions: ['step 1', 'step 2', 'step 3']},
        // {url: 'url2', name: 'name2', category: 'drinks', ingredients: ['ingredient1', 'ingredient 2', 'ingredient 3'], instructions: ['step 1', 'step 2', 'step 3']},
        // {url: 'url3', name: 'name3', category: 'drinks', ingredients: ['ingredient1', 'ingredient 2', 'ingredient 3'], instructions: ['step 1', 'step 2', 'step 3']},
        // {url: 'url4', name: 'name4', category: 'drinks', ingredients: ['ingredient1', 'ingredient 2', 'ingredient 3'], instructions: ['step 1', 'step 2', 'step 3']},
        // {url: 'url5', name: 'name5', category: 'drinks', ingredients: ['ingredient1', 'ingredient 2', 'ingredient 3'], instructions: ['step 1', 'step 2', 'step 3']}
      ]).then(() => {
        return knex.raw("SELECT setval('recipe_id_seq', (SELECT MAX(id) FROM recipe))")
      });
    });
};
